device:
  lcd_rotate: 0  # 0: 0 degree, 1: 90 degree, 2: 180 degree, 3: 270 degree (Left Rotate)

cpu:
  clk_freq_mhz: 160  # operating clock frequency in MHz
  btb_entries: 2024  # the number of BTB entries for branch prediction

memory:
  imem_size_kbyte: 32  # instruction memory size in KByte
  dmem_size_kbyte: 16  # data memory size in KByte
